### ISSUE TITLE
maximum henchmen bug

### ISSUE THREAD

**Issue by JoshuaKunz** [JoshuaKunz/PyDnD#50]
While running the program I found a bug: 

Traceback (most recent call last):
  File "c:\Users\engnd\Desktop\Projects\PyDnD\main.py", line 3, in <module>
    character_creator()
  File "c:\Users\engnd\Desktop\Projects\PyDnD\character\character_creator.py", line 45, in character_creator
    character = set_all_attr_adjust(character)
  File "c:\Users\engnd\Desktop\Projects\PyDnD\character\database\attribute_service.py", line 
317, in set_all_attr_adjust
    character = set_cha_adjust(character)
  File "c:\Users\engnd\Desktop\Projects\PyDnD\character\database\attribute_service.py", line 
268, in set_cha_adjust
    character.maximum_henchmen = values['maximum_henchmen']
KeyError: 'maximum_henchmen'

**Comment by JoshuaKunz** [comment]
Discovery: this is caused by a race subtracting from a 3 attribute roll in cha and choosing a class that has a -1 penalty to cha.
